import "./globals.scss";
import React from "react";
import type { Metadata } from "next";
import MaterialUIProvider from "@/mui/MaterialUIProvider";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<ReduxProvider>
					<MaterialUIProvider>{children}</MaterialUIProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
